var tracery = require('tracery-grammar');

var grammar = tracery.createGrammar({
	"origin": ["#pornigin#", "You Don't Fuck With Me. {img https://loremflickr.com/320/240/mario}", "#penislarge# #flickr#", "#pornigin# #foreign#", "De Imgur Has Spoken {img https://abnuosite.herokuapp.com/imgur.php}", "My new site for you ) http://#letter##letter##letter##letter#.#tld# This website is about #about#", "My cat is being so cute today 🥰  {img https://thiscatdoesnotexist.com}"],
         "pornigin": ["tweet this https://twitter.com/intent/tweet?text=#u##u##u##u##u##u#", "this is #jsonu# tweet", "#completely different#", "MURDERER", "I'm yeeting!", "Reet Tweet Dis! #butt# #butt# #butt# #butt#", "Look at me scat", "0x#hex##hex##hex##hex##hex##hex##hex##hex#", "So i saw my #ornect# #matthew# and i thought \"#react#\"", "MY LATEX BONER! MY LATEX BONER!", "New Oc: #namey##namey# the #butt# #names#!", "LICK MY FEET X3", "Penis expansion? Penis expansion"],
        "htmligin": ["tweet this <a xmlns=\"http://www.w3.org/1999/xhtml\" href=\"https://twitter.com/intent/tweet?text=#u##u##u##u##u##u#\">Tweet!</a>", "this is #jsonu# tweet", "#completely different#", "MURDERER", "I'm yeeting!", "Reet Tweet Dis! #butt# #butt# #butt# #butt#", "Look at me scat", "0x#hex##hex##hex##hex##hex##hex##hex##hex#", "So i saw my #ornect# #matthew# and i thought \"#react#\"", "Nobody:<br xmlns=\"http://www.w3.org/1999/xhtml\"  />Literally Nobody:<br xmlns=\"http://www.w3.org/1999/xhtml\"  />Me: #htmligin#", "MY LATEX BONER! MY LATEX BONER!"],
        "butt": ["sexy", "farting", "farty", "scat", "at", "scatgirls.com"],
        "about": ["mario games, flash mario, online, unblocked", "discord unblocked", "unblocked games", "girl games, foot doctor elsa", "elsa pregnant spiderman"],
        "matthew": ["farting", "yeeting", "dabbing", "derping", "fiting", "meming"],
        "ornect": ["butt", "arm", "penis", "special seat", "doritos", "yeetos", "YeetosDoritos", "ena body pillow"],
        "react": ["Wat De Frucc?", "Ooohhhohoh Yeeees!", "This is sexy.", "Do it more!", "Nice", "No", "Stop", "Bad"],
        "hex": ["A", "B", "C", "D", "E", "F", "G", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
        "search": ["mario", "ass", "boobs", "funny", "memes", "rage+comics", "rage%20comics", "mario%20memes", "gangster%20elmo", "tickle%20kenny%20afton"],
        "flickr": "{svg <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" height=\"240\" width=\"320\"><image height=\"240\" width=\"320\" xlink:href=\"https://loremflickr.com/320/240/#search#\" /></svg>}",
         "rawkr": "https://loremflickr.com/320/240/#search#",
        "foreign": "{svg <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" height=\"500\" width=\"500\"><foreignObject x=\"0\" y=\"0\" height=\"500\" width=\"500\"><p xmlns=\"http://www.w3.org/1999/xhtml\" style=\"color:red;\">#htmligin#</p><img xmlns=\"http://www.w3.org/1999/xhtml\" src=\"#picsites#\" /><p id=\"textor\" xmlns=\"http://www.w3.org/1999/xhtml\" style=\"color:red;\"></p></foreignObject><script type=\"text/javascript\">document.getElementById('textor')[0].innerText=new Date().getTime() + ' - ' + navigator.userAgent;</script></svg>}",
        "u": "%#hex##hex#",
         "penislarge": ["Hey now!", "Look at this funny meme i found", "My friend showed me this pic thought i would share it", "Tickle Time!"],
        "namey": ["Blorple", "Blorgle", "Glorgle", "Glorpus", "Gloopglop", "Zibber", "Glop", "Glonk", "Glarpue", "Zabba", "Glergoo"],
        "hexlow": ["a", "b", "c", "d", "e", "f", "g", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
         "sam": ["Don't forget to like, comment, and subscribe!", "You sound like you need a pic #flickr#", "You know i could fart on you but my farts need to be sexier", "The radiating foot aura?"],
         "tld": ["com", "biz", "net", "org", "info", "io"],
         "letter": ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
         "imgur": "{img https://abnuosite.herokuapp.com/imgur.php}",
        "imgurpic": "{svg <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" height=\"500\" width=\"500\"><image height=\"500\" width=\"500\" xlink:href=\"https://imgur.com/#letter##letter##letter##letter##letter#\" /></svg>}",
        "jsonu": "\\u#hexlow##hexlow##hexlow##hexlow#",
	"alternatives": ["an example", "a different", "another", "a possible", "a generated", "your next"],
        "picsites": ["#rawkr#", "https://abnuosite.herokuapp.com/imgur.php"],
        "names": [
		"angel",
		"brownie",
		"bugbear",
		"centaur",
		"chimera",
		"chupacabra",
		"cockatrice",
		"cyclops",
		"demon",
		"djinn",
		"dragon",
		"draugr",
		"dryad",
		"dwarf",
		"elemental",
		"elf",
		"fairy",
		"faun",
		"frost giant",
		"gargoyle",
		"genie",
		"ghast",
		"ghost",
		"ghoul",
		"giant",
		"gnome",
		"goblin",
		"golem",
		"gorgon",
		"gremlin",
		"griffon",
		"hag",
		"harpy",
		"hippogriff",
		"hobgoblin",
		"homonculus",
		"hydra",
		"imp",
		"incubus",
		"kappa",
		"kobold",
		"kraken",
		"lamassu",
		"leprechaun",
		"lich",
		"manticore",
		"mermaid",
		"merman",
		"minotaur",
		"mummy",
		"naga",
		"nix",
		"nymph",
		"ogre",
		"oni",
		"orc",
		"pegasus",
		"phoenix",
		"pixie",
		"poltergeist",
		"roc",
		"sasquatch",
		"satyr",
		"selkie",
		"siren",
		"spectre",
		"sphinx",
		"sprite",
		"succubus",
		"sylph",
		"thunderbird",
		"troll",
		"unicorn",
		"vampire",
		"valkyrie",
		"warg",
		"wendigo",
		"werewolf",
		"wight",
		"witch",
		"wraith",
		"wyvern",
		"yeti",
		"zombie"
	],
	"completely different": ["and now for something completely different", "so long and thanks for all the fish", "or, maybe, #alternatives# badger"]
});

grammar.addModifiers(tracery.baseEngModifiers); 

console.log(grammar.flatten('#origin#'));
